# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/61e6931f-b791-47a3-93b2-7268f7c801c1";
      fsType = "ext4";
    };

  swapDevices = [ ];

  
  nix.maxJobs = lib.mkDefault 1;
  nixpkgs.config.allowUnfree = true;
  virtualisation.virtualbox.host.enable = true; 
  virtualisation.virtualbox.guest.enable = true;
}
